/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.library_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Book extends javax.swing.JFrame {

    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
    }

   private static final String username ="root"; 
   private static final String password ="Campmake96"; 
   private static final String dataconnect ="jdbc:mysql://localhost:3306/e-library_system"; 
   
    Connection connect = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    DefaultTableModel de;
     int q ,i ,id ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
      public void updateDB() 
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
        connect =DriverManager.getConnection(dataconnect ,username ,password);
        pst =connect.prepareStatement("Select * from book");
        rs = pst.executeQuery();
        java.sql.ResultSetMetaData stdata = rs.getMetaData();
         q = stdata.getColumnCount();
         
         
          DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
         RecordTable.setRowCount(0);
        while(rs.next())
        {
        Vector columbaData = new Vector();
       // idbook, Bookname, Catergory, Author, Publisher, Contents, NoOfPages, Edition
      
        for(i =1;i <=q ;i++)
        {
        columbaData.add(rs.getString("idbook"));
        columbaData.add(rs.getString("Bookname"));
        columbaData.add(rs.getString("Catergory"));
        columbaData.add(rs.getString("Author"));
         columbaData.add(rs.getString("Publisher"));
        columbaData.add(rs.getString("Contents"));
        columbaData.add(rs.getString("NoOfPages"));
        columbaData.add(rs.getString("Edition"));
        
        
        
        }

        RecordTable.addRow(columbaData);
        
        }
        
        
    }  catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "error");
       }
    
    }
      
      public void cat()//work on it
      {
      String sql ="Select * from catergory";
        try{
           pst = connect.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next())
           {
           Catergorycmb.addItem(rs.getString("catergory"));
           }
           
        }catch(Exception ax)
        {
        
        }
        
      }
      public void Aut()//work on it
      {
      String sql ="Select * from author";
        try{
           pst = connect.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next())
           {
           Authorcmb.addItem(rs.getString("Name"));
           }
           
        }catch(Exception ax)
        {
        
        }
        
      }
      
      public void pub()//work on it
      {
      String sql ="Select * from publisher";
        try{
           pst = connect.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next())
           {
           Publishercmb.addItem(rs.getString("Name"));
           }
           
        }catch(Exception ax)
        {
        
        }
        
      }


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BookName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddBook = new javax.swing.JButton();
        BookUpdate = new javax.swing.JButton();
        BookDelete = new javax.swing.JButton();
        BookCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BookPages = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BookContents = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BookEdition = new javax.swing.JTextField();
        Catergorycmb = new javax.swing.JComboBox<>();
        Authorcmb = new javax.swing.JComboBox<>();
        Publishercmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Catergory :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author :");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "BookName", "Catergory", "Author", "Publisher", "Content", "No Of Pages", "Edition"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        AddBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddBook.setText("Add");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        BookUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BookUpdate.setText("Update");
        BookUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookUpdateActionPerformed(evt);
            }
        });

        BookDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BookDelete.setText("Delete");
        BookDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDeleteActionPerformed(evt);
            }
        });

        BookCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BookCancel.setText("Cancel");
        BookCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Publisher :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contents :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Of Pages");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edition");

        Catergorycmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Catergorycmb.setToolTipText("");
        Catergorycmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatergorycmbActionPerformed(evt);
            }
        });

        Authorcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Authorcmb.setToolTipText("");

        Publishercmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Publishercmb.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(AddBook)
                .addGap(54, 54, 54)
                .addComponent(BookUpdate)
                .addGap(48, 48, 48)
                .addComponent(BookDelete)
                .addGap(42, 42, 42)
                .addComponent(BookCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(BookPages, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Authorcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BookEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BookName)
                                    .addComponent(Catergorycmb, 0, 266, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BookContents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Publishercmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 282, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Catergorycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Authorcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Publishercmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BookContents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(BookPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(BookEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBook)
                    .addComponent(BookUpdate)
                    .addComponent(BookDelete)
                    .addComponent(BookCancel))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelcetedRow = jTable1.getSelectedRow();

        BookName.setText(RecordTable.getValueAt(jTable1.getSelectedRow(), 1).toString());
        Catergorycmb.setSelectedItem(RecordTable.getValueAt(jTable1.getSelectedRow(), 2).toString());
        Authorcmb.setSelectedItem(RecordTable.getValueAt(jTable1.getSelectedRow(), 3).toString());
        Publishercmb.setSelectedItem(RecordTable.getValueAt(jTable1.getSelectedRow() ,4).toString());
        BookContents.setText(RecordTable.getValueAt(jTable1.getSelectedRow(), 5).toString());
        BookPages.setText(RecordTable.getValueAt(jTable1.getSelectedRow(), 1).toString());
        BookEdition.setText(RecordTable.getValueAt(jTable1.getSelectedRow(), 5).toString());
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void BookUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookUpdateActionPerformed
             try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        connect = DriverManager.getConnection(dataconnect ,username ,password);
        de =(DefaultTableModel)jTable1.getModel();
        int selected =jTable1.getSelectedRow();
        id =Integer.parseInt(de.getValueAt(selected, 0).toString());
        pst = connect.prepareStatement("update book set Bookname =?, Catergory=?, Author=?, Publisher=?, Contents=?, NoOfPages=?, Edition=? where idbook =? ");
      
        
        
            
            pst.setString(1, BookName.getText());
            pst.setString(2, Catergorycmb.getSelectedItem().toString());
            pst.setString(3, Authorcmb.getSelectedItem().toString());
            pst.setString(4, Publishercmb.getSelectedItem().toString());
            pst.setString(5, BookContents.getText());
            pst.setString(6, BookPages.getText());
            pst.setString(7, BookEdition.getText());
            pst.setInt(8, id);
            
            

        pst.executeUpdate();
        updateDB();
        JOptionPane.showMessageDialog(this, "Successfully updated");
        
        }
           catch(Exception as)
           {
               System.out.println(as);
           JOptionPane.showMessageDialog(null, "Erooor");
           }
    }//GEN-LAST:event_BookUpdateActionPerformed

    private void BookCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookCancelActionPerformed
       setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
        
    }//GEN-LAST:event_BookCancelActionPerformed

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
            try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connect =DriverManager.getConnection(dataconnect ,username ,password);
            pst =connect.prepareStatement("insert into book (Bookname, Catergory, Author, Publisher, Contents, NoOfPages, Edition) value(?,?,?,?,?,?,?)");
            //Storing
            pst.setString(1, BookName.getText());
            pst.setString(2, Catergorycmb.getSelectedItem().toString());
            pst.setString(3, Authorcmb.getSelectedItem().toString());
            pst.setString(4, Publishercmb.getSelectedItem().toString());
            pst.setString(5, BookContents.getText());
            pst.setString(6, BookPages.getText());
            pst.setString(7, BookEdition.getText());
            
            
            
            
            
            pst.executeUpdate();

            
           JOptionPane.showMessageDialog(null, "The Book has sucessfully added");
           updateDB();
            
           
            
            
            
        }catch(Exception ex)
        {
            System.out.println(ex);
            
        }
                                         
    }//GEN-LAST:event_AddBookActionPerformed

    private void BookDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookDeleteActionPerformed
       de =(DefaultTableModel)jTable1.getModel();
        int selected =jTable1.getSelectedRow();
        id =Integer.parseInt(de.getValueAt(selected, 0).toString());
       
        
        try{
        pst =connect.prepareStatement("Delete from book   where idbook =?");
        pst.setInt(1, id);
        //int rowsAffected = stmt.executeUpdate(deleteQuery);
        pst.executeUpdate();
        updateDB();
        JOptionPane.showMessageDialog(null,"Record deleted");
        
        
            BookName.setText("");
            Catergorycmb.setSelectedItem("");
            Authorcmb.setSelectedItem("");
            Publishercmb.setSelectedItem("");
            BookContents.setText("");
            BookPages.setText("");
            BookEdition.setText("");
            
        
           // pst.executeQuery();
            
        
        }
        catch(Exception a){
        JOptionPane.showMessageDialog(null, a);
            System.out.println(a);
        }
    }//GEN-LAST:event_BookDeleteActionPerformed

    private void CatergorycmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatergorycmbActionPerformed
        String sql ="Select * from catergory";
        try{
           pst = connect.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next())
           {
           Catergorycmb.addItem("catergory");
           }
           
        }catch(Exception ax)
        {
        
        }
    }//GEN-LAST:event_CatergorycmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JComboBox<String> Authorcmb;
    private javax.swing.JButton BookCancel;
    private javax.swing.JTextField BookContents;
    private javax.swing.JButton BookDelete;
    private javax.swing.JTextField BookEdition;
    private javax.swing.JTextField BookName;
    private javax.swing.JTextField BookPages;
    private javax.swing.JButton BookUpdate;
    private javax.swing.JComboBox<String> Catergorycmb;
    private javax.swing.JComboBox<String> Publishercmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
